# Generated by Django 3.1.7 on 2021-04-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='confirmed',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='activated_at',
            new_name='confirmed_at',
        ),
    ]
