# Generated by Django 3.1.7 on 2021-04-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210412_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='description',
            field=models.TextField(default='lorem ipsum dolor sit amet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banreason',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
