# Generated by Django 3.1.7 on 2021-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210412_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='banned_at',
            field=models.DateTimeField(),
        ),
    ]
