# Generated by Django 3.1.7 on 2021-04-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210412_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='banreason',
            name='days',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
