version: "3.8"

services:
    edc_users_django:
        container_name: edc_users_django
        build: .
        volumes:
            - .:/code
            - ./docker/users/static:/code/static
        env_file:
            - .env

    edc_users_nginx:
        container_name: edc_users_nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/users/static:/code/static
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - edc_users_django
        environment:
            - VIRTUAL_HOST=${SERVICE_USERS_DNS}
            - LETSENCRYPT_HOST=${SERVICE_USERS_DNS}
            - LETSENCRYPT_EMAIL=${SSL_LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: edcNet
