version: "3.3"

services:
    users_psql:
        container_name: users_psql
        image: postgres
        restart: always
        ports:
            - ${APP_DB_PORT:-5432}:5432
        volumes:
            - usersPsqlVolume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${APP_DB_NAME:-users}
            POSTGRES_USER: ${APP_DB_USER:-admin}
            POSTGRES_PASSWORD: ${APP_DB_PASS:-secret}
        networks:
            - usersNet

    users_django:
        container_name: users_django
        build: .
        volumes:
            - ./docker/django/static:/code/static
            - .:/code
        depends_on:
            - users_psql
        env_file:
            - .env
        networks:
            - usersNet

    users_nginx:
        container_name: users_nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/django/static:/code/static
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - users_django
        networks:
            - usersNet

    users_redis:
        container_name: users_redis
        image: redis:6
        restart: always
        networks:
            - usersNet

networks:
    usersNet:
        driver: "bridge"

volumes:
    usersPsqlVolume:
